### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by Pelirrojo** [FranciscoJAM/PracticaFinalVisualizacionAvanzadaFrancisco#1]
Hola,

He intentado arrancar el código con la ayuda del siguiente docker-compose:
https://github.com/moyed/docker-compose-lamp-stack/tree/master/docker-lamp

1. he modificado el Dockerfile para que el usuario root tenga de contraseña 'root' en mysql
2. He accedido al primer contenedor (php) y he montado el código como directorio en /var/www/html
3. He renombrado y modificado el fichero .env.example ->  .env con db en lugar de localhost (nombre del 2º contenedor)
4. He accedido al segundo contenedor (mysql) y he descargado por curl los datos de github además de insertarlos en BBDD con mysql productionsojavictor < productionsojavictor.sql -p root
5. He abierto localhost:8000/public en mi navegador
6. La web carga y veo el informe se ve pero no consigo ver el gráfico.

Creo que faltan configuraciones para el Virtual Host de Laravel.
¿Me puedes ayudar? O dar más indicaciones al respecto.

Un saludo,
Manuel

**Comment by FAGUILERAM** [comment]
Hola Manuel,


Disculpa pero nunca miro este correo... no se si ya estoy a tiempo para poder ayudarte o no, para el  tema de la nota. De todas formas mi correo personal es franaguileramatas@gmail.com , este es el  correo que miro diariamente.


Disculpe las molestias,


Muchas gracias,


Saludos, Francisco.

________________________________
De: Manuel Eusebio de Paz Carmona <notifications@github.com>
Enviado: lunes, 14 de mayo de 2018 17:45:59
Para: FranciscoJAM/PracticaFinalVisualizacionAvanzadaFrancisco
Cc: Subscribed
Asunto: [FranciscoJAM/PracticaFinalVisualizacionAvanzadaFrancisco] Dudas (#1)


Hola,

He intentado arrancar el código con la ayuda del siguiente docker-compose:
https://github.com/moyed/docker-compose-lamp-stack/tree/master/docker-lamp

  1.  he modificado el Dockerfile para que el usuario root tenga de contraseña 'root' en mysql
  2.  He accedido al primer contenedor (php) y he montado el código como directorio en /var/www/html
  3.  He renombrado y modificado el fichero .env.example -> .env con db en lugar de localhost (nombre del 2º contenedor)
  4.  He accedido al segundo contenedor (mysql) y he descargado por curl los datos de github además de insertarlos en BBDD con mysql productionsojavictor < productionsojavictor.sql -p root
  5.  He abierto localhost:8000/public en mi navegador
  6.  La web carga y veo el informe se ve pero no consigo ver el gráfico.

Creo que faltan configuraciones para el Virtual Host de Laravel.
¿Me puedes ayudar? O dar más indicaciones al respecto.

Un saludo,
Manuel
